# **MÓDULO 39 - Exercicio - Aplicando XGboost**

Nessa atividade vocês usarão uma base já connhecida, a base de propensão a compra de carros.
Já utilizamos essa base antes, nessa atividade, você deve carregar a base, realizar os tratamentos necessários, rodar o XGBoost, encontrar as principais variaveis.
Vamos lá!

In [1]:
import xgboost as xgb
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

# 1. Carrega a base de dados, verifique os tipos de dados, dados faltantes e drop a coluna ID.

In [2]:
#SEU CÓDIGO AQUI

## A) Carregamento da base de dados

In [ ]:
# Carregamento da base de dados
base = pd.read_csv('CARRO_CLIENTES.csv', delimiter=',')

# Exibição da base
base

     User ID  Gender  Age  AnnualSalary  Purchased
0        385    Male   35         20000          0
1        681    Male   40         43500          0
2        353    Male   49         74000          0
3        895    Male   40        107500          1
4        661    Male   25         79000          0
..       ...     ...  ...           ...        ...
995      863    Male   38         59000          0
996      800  Female   47         23500          0
997      407  Female   28        138500          1
998      299  Female   48        134000          1
999      687  Female   44         73500          0

[1000 rows x 5 columns]

## B) Verificação dos tipos de dados

In [5]:
# Verificação dos tipos de dados da base
base.dtypes

User ID          int64
Gender          object
Age              int64
AnnualSalary     int64
Purchased        int64
dtype: object

A única variável categórica (**tipo object**) identificada na base é `Gender`. Para viabilizar o treinamento do XGBoost, que exige exclusivamente dados numéricos, essa coluna será processada via LabelEncoder posteriormente.

## C) Verificação dos dados faltantes e tratamento

In [6]:
# Verificação dos valores nulos na base
base.isnull().sum()

User ID         0
Gender          0
Age             0
AnnualSalary    0
Purchased       0
dtype: int64

Como a base de dados não apresenta valores nulos, a etapa de imputação ou eliminação de dados faltantes será dispensada, permitindo avançar para outros processo e etapdas.

## D) Drop da coluna "User ID"

A exclusão da coluna `User ID` é necessária porque, embora seja do tipo numérico (**int**), ela representa apenas um identificador único do cliente. Por não carregar valor estatístico ou padrão comportamental, sua permanência geraria ruído desnecessário no treinamento do XGBoost.

In [8]:
# Exclusão da coluna 'User ID' da base
base = base.drop('User ID', axis=1)

# Exibição da base após a exclusão da coluna
base

     Gender  Age  AnnualSalary  Purchased
0      Male   35         20000          0
1      Male   40         43500          0
2      Male   49         74000          0
3      Male   40        107500          1
4      Male   25         79000          0
..      ...  ...           ...        ...
995    Male   38         59000          0
996  Female   47         23500          0
997  Female   28        138500          1
998  Female   48        134000          1
999  Female   44         73500          0

[1000 rows x 4 columns]

# 2. Aplique o Label Encoder para a coluna Gender e exclua a coluna categórica.

In [ ]:
#SEU CÓDIGO AQUI

In [9]:
# Chamando a função Label Encoder
label_encoder = LabelEncoder()

# Aplicação do Label Encoder na coluna categórica 'Gender'
base['Gender'] = label_encoder.fit_transform(base['Gender'])

In [11]:
# Verificação da trasnformação da coluna 'Gender' para valores numéricos
base.dtypes['Gender']

dtype('int64')

In [12]:
# Verificação da base após a transformação da coluna 'Gender'
base

     Gender  Age  AnnualSalary  Purchased
0         1   35         20000          0
1         1   40         43500          0
2         1   49         74000          0
3         1   40        107500          1
4         1   25         79000          0
..      ...  ...           ...        ...
995       1   38         59000          0
996       0   47         23500          0
997       0   28        138500          1
998       0   48        134000          1
999       0   44         73500          0

[1000 rows x 4 columns]

# 3. Faça a matriz de correlação e analise as váriaveis que parecem ter maior correlação com a váriavel target.

In [ ]:
#SEU CÓDIGO AQUI

# 4. Faça a separação da base em X e Y e em seguida nas bases de treino e teste.

In [ ]:
#SEU CÓDIGO AQUI

# 5. Treino o modelo Xgboost com sua base de treino.
Pesquise alguns hyperparametros na bibllioteca para utilizar, utilize ao menos 2.

In [11]:
#SEU CÓDIGO AQUI

# 6. Realize as previsões para a base de teste e traga as probabilidades das previsões.

In [ ]:
#SEU CÓDIGO AQUI

# 7. Faça a transformação das probabilidades nas previsões binárias e avalie o desempenho do modelo.

In [ ]:
#SEU CÓDIGO AQUI

# 8. Traga a lista com a feature importance.
As features mais importantes são as mesmas que indicaram maior correlação na matriz de correlação?

In [ ]:
#SEU CÓDIGO AQUI